# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = "purah"
py_version = "3.7"
version = "0.1.0"


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
django = "^3.0.5"
discord-py = "^1.3.3"
click = "^7.1.1"
aiocache = {version = "^0.11.1", extras=["redis"]}


[tool.pyflow.dev-dependencies]

