# Generated by Django 3.1.4 on 2020-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion
import extensions.ssbu.dsr
import hero.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
        ('ssbu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='checkin_emoji',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='signup_emoji',
        ),
        migrations.RemoveField(
            model_name='tournamentseries',
            name='checkin_emoji',
        ),
        migrations.RemoveField(
            model_name='tournamentseries',
            name='signup_emoji',
        ),
        migrations.AddField(
            model_name='game',
            name='player_1_fighter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_fighter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ruleset',
            field=hero.fields.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='ssbu.ruleset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruleset',
            name='dsr_variation',
            field=extensions.ssbu.dsr.DSRField(default=extensions.ssbu.dsr.DSR['on'], max_length=32),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='first_to_strike',
            field=hero.fields.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='needs_confirmation_by',
            field=hero.fields.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='suggested_by',
            field=hero.fields.UserField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=hero.fields.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=hero.fields.UserField(on_delete=django.db.models.deletion.CASCADE, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=hero.fields.UserField(on_delete=django.db.models.deletion.CASCADE, to='hero.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='wins_required',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ruleset',
            field=hero.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssbu.ruleset'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleset',
            unique_together={('name', 'guild', 'version')},
        ),
        migrations.RemoveField(
            model_name='ruleset',
            name='dsr',
        ),
    ]
