# Generated by Django 3.1.4 on 2020-12-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0002_auto_20201221_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='when',
            new_name='started_at',
        ),
    ]
