# Generated by Django 3.1.4 on 2020-12-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0003_auto_20201222_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
