# Generated by Django 3.1.4 on 2020-12-22 13:14

from django.db import migrations
import django.db.models.deletion
import hero.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0004_match_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ruleset',
            field=hero.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssbu.ruleset'),
        ),
    ]
