# Generated by Django 3.1.4 on 2020-12-22 16:40

from django.db import migrations
import django.db.models.deletion
import hero.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
        ('ssbu', '0005_auto_20201222_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=hero.fields.UserField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.User'),
        ),
    ]
