# Generated by Django 3.1.4 on 2020-12-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0007_auto_20201222_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
