# Generated by Django 3.1.4 on 2020-12-28 11:11

from django.db import migrations
import django.db.models.deletion
import hero.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
        ('ssbu', '0008_auto_20201226_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildplayer',
            old_name='guild_elo',
            new_name='elo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='last_game_won_by',
        ),
        migrations.AddField(
            model_name='match',
            name='match_end_message',
            field=hero.fields.MessageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.Message'),
        ),
    ]
