# Generated by Django 3.1.4 on 2020-12-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0009_auto_20201228_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleset',
            options={'get_latest_by': 'version'},
        ),
    ]
