# Generated by Django 3.1.4 on 2020-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0011_auto_20201228_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchoffer',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
