# Generated by Django 3.1.4 on 2020-12-29 12:16

from django.db import migrations
import django.db.models.deletion
import hero.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0012_matchoffer_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsetup',
            name='default_ruleset',
            field=hero.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssbu.ruleset'),
        ),
    ]
