# Generated by Django 3.1.4 on 2021-01-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0013_guildsetup_default_ruleset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildplayer',
            old_name='elo',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='guildsetup',
            old_name='show_elo',
            new_name='show_rating',
        ),
        migrations.RenameField(
            model_name='guildsetup',
            old_name='use_elo',
            new_name='use_rating',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='elo',
            new_name='rating',
        ),
    ]
