# Generated by Django 3.1.4 on 2021-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0015_auto_20210102_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildplayer',
            name='deviation',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='guildplayer',
            name='volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_global_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_global_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_global_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_global_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_global_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_global_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='deviation',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='player',
            name='volatility',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(db_index=True, default=1500),
        ),
    ]
