# Generated by Django 3.1.4 on 2021-01-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0016_auto_20210102_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildplayer',
            name='rating',
            field=models.IntegerField(db_index=True, default=1500),
        ),
    ]
