# Generated by Django 3.1.4 on 2021-01-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0017_auto_20210102_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deviation',
            field=models.IntegerField(default=50),
        ),
    ]
