# Generated by Django 3.1.4 on 2021-01-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbu', '0018_auto_20210102_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deviation',
            field=models.IntegerField(default=350),
        ),
    ]
